### ISSUE TITLE
Rename patch file

### ISSUE THREAD

**Issue by mistyron** [MistySOM/meta-mistysom#12]
Sorry, this slipped through at the PR review:
Rename the patch file, call it something like `0005-add-scif2-serial-port-for-uart.patch` instead to describe the functionality it enables. 
https://github.com/MistySOM/meta-mistysom/blob/2886ed8acc705b343cace6209d25557f15ecf226/recipes-kernel/linux/linux-renesas_%25.bbappend#L7
Also rename `0006-add-riic1-i2c1-for-testing-i2c-on-hdr.patch` to `0006-add-riic1.patch` instead, change it for both, g2l & v2l, please.

**Comment by matinlotfali** [comment]
@mistyron Is this still relevant?

**Comment by mistyron** [comment]
No, it doesn't look like it. Closing!
