### ISSUE TITLE
rename recipes-connectivity in meta-mistysom

### ISSUE THREAD

**Issue by mistyron** [MistySOM/meta-mistysom#13]
I recommend we rename the `recipes-connectivity/` in `meta-mistysom` to avoid confusion with `meta-openembedded/meta-python/recipes-connectivity`, thoughts?

**Comment by matinlotfali** [comment]
Actually `meta-openembedded/meta-python/recipes-connectivity` was my inspiration to choose the name and I thought we are following the same naming convention. 
Similar to `recipes-core` and `recipes-kernel`. Don't they also cause confusion?

**Comment by mistyron** [comment]
no but it's not clear what is referred to by just referring to `recipes-connectivity/`, why don't we call it `recipes-networklink/` or  `recipes-communication/` or something instead? Just to avoid any ambiguity, I'm thinking

**Comment by matinlotfali** [comment]
I like `recipes-network`

**Comment by mistyron** [comment]
Sounds good, do it! :)
